package com.mehmandarov.llmvalidation.chapter3_validation;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Chapter 3: Code Execution — Let the LLM Write the Formula, We Execute It.
 *
 * <p>Instead of asking the LLM "what is the total?", ask it to <em>generate
 * the arithmetic expression</em> (e.g. {@code "750 + 250 + 125.50"}).
 * Then we evaluate the expression deterministically in Java.</p>
 *
 * <p>This is a simple, safe evaluator that only handles {@code +}, {@code -},
 * {@code *}, {@code /} on decimal numbers. No variables, no function calls,
 * no code injection risk.</p>
 *
 * <p><b>Key insight for the talk:</b> The <em>generation</em> is probabilistic
 * (the LLM might get the formula wrong), but the <em>execution</em> is
 * deterministic. And a wrong formula is easier to validate than a wrong answer.</p>
 */
public class ExpressionEvaluator {

    private static final Logger log = LoggerFactory.getLogger(ExpressionEvaluator.class);

    // Only allow digits, decimal points, whitespace, and basic arithmetic operators
    private static final Pattern SAFE_EXPRESSION = Pattern.compile("^[\\d.+\\-*/ ()]+$");
    private static final Pattern NUMBER = Pattern.compile("\\d+\\.?\\d*");

    /**
     * Evaluates a simple arithmetic expression safely.
     *
     * @param expression e.g. "750 + 250 + 125.50"
     * @return the result, e.g. 1125.50
     * @throws IllegalArgumentException if the expression contains unsafe characters
     * @throws ArithmeticException if the expression is malformed
     */
    public BigDecimal evaluate(String expression) {
        if (expression == null || expression.isBlank()) {
            throw new IllegalArgumentException("Expression is empty");
        }

        String trimmed = expression.trim();

        // Safety check: reject anything that isn't numbers and basic operators
        if (!SAFE_EXPRESSION.matcher(trimmed).matches()) {
            log.warn("🚫 UNSAFE EXPRESSION rejected: '{}'", trimmed);
            throw new IllegalArgumentException(
                    "Expression contains unsafe characters: " + trimmed);
        }

        log.info("🧮 CODE EXECUTION: evaluating '{}'", trimmed);
        BigDecimal result = parseExpression(trimmed);
        log.info("🧮 CODE EXECUTION: '{}' = {}", trimmed, result);
        return result.setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Validates that an LLM-generated expression produces the expected result.
     *
     * @param expression   the formula generated by the LLM
     * @param claimedTotal the total the LLM claims
     * @return true if the expression evaluates to the claimed total
     */
    public boolean verify(String expression, BigDecimal claimedTotal) {
        try {
            BigDecimal actual = evaluate(expression);
            boolean match = actual.compareTo(claimedTotal.setScale(2, RoundingMode.HALF_UP)) == 0;
            if (match) {
                log.info("✅ Expression '{}' matches claimed total {}", expression, claimedTotal);
            } else {
                log.warn("❌ Expression '{}' = {} but LLM claimed {}", expression, actual, claimedTotal);
            }
            return match;
        } catch (Exception e) {
            log.warn("❌ Failed to evaluate expression '{}': {}", expression, e.getMessage());
            return false;
        }
    }

    // ── Simple recursive-descent parser for +, -, *, / ──────────────────

    private int pos;
    private String expr;

    private synchronized BigDecimal parseExpression(String input) {
        this.expr = input.replaceAll("\\s+", "");
        this.pos = 0;
        BigDecimal result = parseAddSub();
        if (pos < expr.length()) {
            throw new ArithmeticException("Unexpected character at position " + pos + ": " + expr.charAt(pos));
        }
        return result;
    }

    private BigDecimal parseAddSub() {
        BigDecimal left = parseMulDiv();
        while (pos < expr.length() && (expr.charAt(pos) == '+' || expr.charAt(pos) == '-')) {
            char op = expr.charAt(pos++);
            BigDecimal right = parseMulDiv();
            left = (op == '+') ? left.add(right) : left.subtract(right);
        }
        return left;
    }

    private BigDecimal parseMulDiv() {
        BigDecimal left = parseAtom();
        while (pos < expr.length() && (expr.charAt(pos) == '*' || expr.charAt(pos) == '/')) {
            char op = expr.charAt(pos++);
            BigDecimal right = parseAtom();
            left = (op == '*') ? left.multiply(right)
                    : left.divide(right, 10, RoundingMode.HALF_UP);
        }
        return left;
    }

    private BigDecimal parseAtom() {
        if (pos < expr.length() && expr.charAt(pos) == '(') {
            pos++; // skip '('
            BigDecimal result = parseAddSub();
            if (pos < expr.length() && expr.charAt(pos) == ')') {
                pos++; // skip ')'
            }
            return result;
        }

        Matcher matcher = NUMBER.matcher(expr.substring(pos));
        if (matcher.lookingAt()) {
            String matched = matcher.group();
            pos += matched.length();
            return new BigDecimal(matched);
        }
        throw new ArithmeticException("Expected number at position " + pos);
    }
}

